# apiVersion: v1
# kind: Pod
# metadata:
#   name: posts
# spec:
#   containers:
#     - name: posts
#       image: navi23/mini-blog-post:latest
#       imagePullPolicy: Never

## We will not create seperate service and pods.. we will create it together with deployment
